export const WHATSAPP_NUMBER = '+2348130812073'
export const PHONE_NUMBER = '+2348130812073'
export const PHONE_DISPLAY = '+234 813 081 2073'
export const EMAIL = 'danielprince308120@gmail.com'
export const COMPANY_NAME = 'Daniel Prince Generator Services and Sales'
export const SITE_URL = 'https://dpe-engine-solutions.vercel.app'
export const SITE_DESCRIPTION = 'Generator sales, engine parts supply, repair and cleaning services in Lagos. Call or WhatsApp us for fast response.'
